import { ProjectMeta } from "../types/types";

/* =============================================
   BULK ISSUE REPORTS
   - Functions to display decorative headers and summaries
   - Supports Dry Run and Real execution modes
============================================= */

/**
 * Prints a professional decorative header for bulk issue operations.
 * Shows project metadata, source file info, and execution mode.
 * @param meta - Project metadata (name, author, repository)
 * @param fileName - Name of the JSON source file
 * @param absolutePath - Full system path to the source file
 * @param isDryRun - True if execution is a simulation
 */
export function printHeader(meta: ProjectMeta, fileName: string, absolutePath: string, isDryRun: boolean): void {
  console.log("\n" + "━".repeat(65));
  console.log("\n" + "━".repeat(65));
  console.log(`🚀 PROJECT: ${meta.name.toUpperCase()}`);
  console.log(`👤 OWNER:   7eightDev`);
  console.log(`✍️  AUTHOR:  ${meta.author}`);
  console.log(`🔗 REPO:    ${meta.repository}`);
  console.log(`📂 SOURCE:  ${fileName}`);
  console.log(`📍 PATH:    ${absolutePath}`);
  console.log(`🛠️  MODE:    ${isDryRun ? "🔍 DRY RUN (Simulation)" : "🚀 EXECUTION (Real)"}`);
  console.log("━".repeat(65));
  console.log("━".repeat(65));
  console.log(" ".repeat(65));
}


/**
 * Prints a final execution summary for bulk issue operations.
 * Provides statistics for created, skipped, and total issues.
 * @param projectName - Name of the project being processed
 * @param stats - Object containing statistics (created, skipped, total)
 * @param isDryRun - True if this is a simulation
 */
export function printSummary(projectName: string, stats: { created: number; skipped: number; total: number }, isDryRun: boolean): void {
  console.log("\n" + "━".repeat(65));
  console.log(`🏁 SUMMARY FOR: ${projectName.toUpperCase()}`);
  console.log("━".repeat(65));

  if (isDryRun) {
    console.log(`📝 Simulation finished.`);
    console.log(`   Pending:  ${stats.total - stats.skipped}`);
    console.log(`   Skipped:  ${stats.skipped}`);
    console.log(`   Total:    ${stats.total}`);
  } else {
    console.log(`   ✅ Created:  ${stats.created}`);
    console.log(`   ⏭️  Skipped:  ${stats.skipped}`);
    console.log(`   📦 Total:    ${stats.total}`);

    if (stats.created > 0) {
      console.log("\n🎉 All issues created successfully!");
    } else if (stats.skipped === stats.total) {
      console.log("\n💡 All issues already created or in test state.");
    }
  }

  console.log("━".repeat(65) + "\n");
}

/* =============================================
   SINGLE ISSUE REPORTS
============================================= */

/**
 * Prints a decorative header for single issue operations.
 * Indicates if Dry Run or Test Mode is active.
 * @param meta - Project metadata
 * @param isDryRun - True if simulation mode
 * @param isTestMode - True if automated test mode
 */
export function printSingleIssueHeader(
  meta: ProjectMeta, 
  isDryRun: boolean, 
  isTestMode: boolean,
): void {
  console.log("\n" + "━".repeat(60));
  console.log(`🚀 PROJECT: ${meta.name.toUpperCase()} v${meta.version}`);
  console.log(`✍️  AUTHOR:  ${meta.author}`);
  console.log(`🔗 REPO:    ${meta.repository}`);
  console.log(
    `🎯 ACTION:  SINGLE ISSUE ${isDryRun ? "(SIMULATION)" : isTestMode ? "(TEST)" : "(REAL)"}`
  );
  console.log("━".repeat(60));
}

/**
 * Prints a success report for a single GitHub issue creation.
 * Includes machine-readable tag for further automation.
 * @param issueNumber - GitHub-assigned issue number
 * @param title - Final prefixed title of the created issue
 */
export function printSingleIssueSuccess(issueNumber: string, title: string): void {
  console.log("\n" + "━".repeat(60));
  console.log(`🚀 ISSUE #${issueNumber} CREATED SUCCESSFULLY!`);
  console.log(`📌 Title:  ${title}`);
  console.log("━".repeat(60));
  console.log(`##ISSUE_NUMBER##${issueNumber}##`);
}

/**
 * @function printTestModeBlock
 * @description Displays a simulated issue creation block for automated testing.
 * *Outputs a mock issue number (999) and the required machine-readable tags.
 * @param {string} title - The final prefixed title of the created issue (e.g., 'ISSUE-123: title').
 * @returns {void}
 */
export function printTestModeBlock(title: string): void {
  console.log("🧪 [TEST_MODE] Simulating issue creation...");
  console.log(`📌 Mock Title: ISSUE-999: ${title}`);
  console.log("━".repeat(60));
  console.log("##ISSUE_NUMBER##999##");
}

/**
 * @function printDryRunBlock
 * @description Displays the simulation summary during a Dry Run, showing the exact command that would be executed.
 * * @param {string} command - The full gh CLI command string generated by the script.
 * @returns {void}
 */
export function printDryRunBlock(command: string): void {
  console.log("🔍 [SIMULATION] Command to be executed:");
  console.log(`\x1b[33m${command}\x1b[0m`);
  console.log("\n✅ Simulation successful. No changes were made to GitHub.");
}